---
- hosts: test
  become: true
  - name: The constraint to apply
    debug: var=item
    with_indexed_items: "{{ tc }}"
    when:
      - item[1].source == ansible_eth0["ipv4"]["address"]

  - name: Removing root qdisc
    shell: "tc qdisc del dev eth0 root || true"

  - name: Preparing htf
    shell: "tc qdisc add dev eth0 root handle 1: htb"

  - name: Apply traffic control constraint
    include: tc.yml args={{ item }}
    with_indexed_items: "{{ tc }}"
    when:
      - item[1].source == ansible_eth0["ipv4"]["address"]
